apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: ref-react-devops--
manifests:
  rawYaml:
    - infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: mehradi/todo-backend
      context: backend
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.*"
    - image: mehradi/todo-frontend
      context: frontend
      docker:
        dockerfile: Dockerfile
        noCache: false
        pullParent: false
        squash: false
      sync:
        manual:
          - dest: .
            src: "src/**/*.*"
